"""add courses

Revision ID: dc675588c682
Revises: 78f6a5bffbae
Create Date: 2025-06-30 00:00:29.153623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc675588c682'
down_revision: Union[str, Sequence[str], None] = '78f6a5bffbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'description_md',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'courses', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.alter_column('courses', 'description_md',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
