"""Add category & subcategory to course

Revision ID: edc239e0cd85
Revises: c2c1e700bb30
Create Date: 2025-06-30 00:30:18.867731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc239e0cd85'
down_revision: Union[str, Sequence[str], None] = 'c2c1e700bb30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('subcategories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategories_slug'), 'subcategories', ['slug'], unique=True)
    op.add_column('courses', sa.Column('curriculum_md', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('category_id', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('subcategory_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'courses', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'courses', 'subcategories', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'subcategory_id')
    op.drop_column('courses', 'category_id')
    op.drop_column('courses', 'curriculum_md')
    op.drop_index(op.f('ix_subcategories_slug'), table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
